version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rhcproc-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6wgf4xmzogo7"
s3_prefix = "rhcproc-api"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
